db/migrate/20190213181121_create_users.rb, db/schema.rb, db/seeds.rb
Added seed data to assure that the models we made were interacting with each other the ways we wanted
closes # 25
=> Adds seed data

app/controllers/api/v1/users_controller.rb, spec/requests/api/v1/user_request_spec.rb
Adds sad path & sad path testing for passwords not matching
closes # 27
=> Adds sad path & sad path test for passwords not matching

README.md, app/models/user.rb, app/serializers/login_serializer.rb, db/seeds.rb, spec/requests/api/v1/login_request_spec.rb
Removes password_digest from login response 
closes # 33
=> 33 password bug

README.md, app/controllers/api/v1/login_controller.rb, app/controllers/api/v1/users_controller.rb, app/serializers/profile_serializer.rb, config/routes.rb, db/seeds.rb, spec/requests/api/v1/user_update_spec.rb
Added endpoint for users updating their info
closes #5
=> 5 update user

README.md, app/controllers/api/v1/locations_controller.rb, app/serializers/location_serializer.rb, config/routes.rb, spec/requests/api/v1/location_request_spec.rb
Create a new endpoint for GET /api/v1/locations which returns all locations seeded in the database. Added tests.  Updated README to include images of endpoints, responses, and requests. 
closes #17
=> 17 get all locations

db/seeds.rb
Added faker data to the seed file
closes #39
=> 39 faker seed data

README.md, app/controllers/api/v1/positions_controller.rb, app/serializers/position_serializer.rb, config/routes.rb, spec/requests/api/v1/position_request_spec.rb
=> 18 get all positions

README.md, app/controllers/api/v1/employers_controller.rb, app/serializers/employer_serializer.rb, config/routes.rb, spec/requests/api/v1/employer_request_spec.rb
=> 16 get all employers

README.md, db/seeds.rb
Adds normalized seed data
closes #
=> Adds normalized seed data

README.md, app/controllers/api/v1/users_controller.rb, app/serializers/user_api_serializer.rb, app/serializers/user_serializer.rb, config/routes.rb, db/seeds.rb, spec/requests/api/v1/user_request_spec.rb
Adds GET users endpoint
closes #3
=> 3 get all users

README.md, app/controllers/api/v1/users_controller.rb, app/models/message.rb, app/serializers/connection_serializer.rb, app/serializers/private_user_serializer.rb, app/serializers/user_serializer.rb, config/routes.rb, spec/requests/api/v1/single_user_request_spec.rb, spec/requests/api/v1/user_request_spec.rb
Added the endpoint to get a single user and all of the sad paths for that
closes #4
=> 4 get single user

README.md, app/controllers/api/v1/users/search_controller.rb, app/controllers/api/v1/users_controller.rb, app/controllers/application_controller.rb, app/models/user.rb, config/routes.rb, db/migrate/20190213180714_create_locations.rb, db/migrate/20190213180848_create_employers.rb, db/migrate/20190213180918_create_positions.rb, db/migrate/20190213181121_create_users.rb, db/schema.rb, spec/requests/api/v1/user_request_spec.rb
=> 19 filter users by name

README.md, app/controllers/api/v1/users_controller.rb, app/models/user.rb, config/routes.rb, spec/requests/api/v1/user_delete_spec.rb, spec/requests/api/v1/user_request_spec.rb
Adds delete endpoint for users
closes #13
=> 13 delete user

README.md, app/controllers/api/v1/users/search_controller.rb, app/models/user.rb, app/serializers/profile_serializer.rb, app/serializers/user_api_serializer.rb, spec/requests/api/v1/user_request_spec.rb
closes #12 
closes #11 
closes #10
=> 12 all filters

README.md, app/controllers/api/v1/login_controller.rb, app/models/user.rb, app/serializers/profile_serializer.rb, spec/requests/api/v1/login_request_spec.rb, spec/requests/api/v1/user_request_spec.rb
When a user logs in, their response will include an array of suggested connections.  Wrote an intense active record/SQL query.  Was not able to figure out how to limit the suggested used to exclude those users with whom the logged in user has already connected.  I have commented out the code that shows the query that would maybe make that work.  At this time, the query is not fully working.
closes #44
=> 44 get suggestions

README.md, app/controllers/api/v1/messages_controller.rb, app/models/message.rb, app/models/user.rb, app/serializers/message_serializer.rb, config/routes.rb, spec/requests/api/v1/login_request_spec.rb, spec/requests/api/v1/message_request_spec.rb
User can get access to all of their messages, regardless of where they were the sender or the receiver.  The response includes info about the message sent and also the name of the sender and the receiver.   I am doing a class method call from the serializer so I'm definitely open to feedback if you can see another way to return the user name for both sender and receiver.
closes #7
=> 7 get messages

config/environments/production.rb
=> Add heroku link to send production config

README.md, app/models/user.rb, spec/models/message_spec.rb, spec/models/user_spec.rb
Adds Model testing for users and messages
closes #60
=> 60 model testing

Gemfile, Gemfile.lock, README.md, app/controllers/api/v1/messages_controller.rb, app/controllers/api/v1/users/messages_controller.rb, app/controllers/api/v1/users_controller.rb, app/mailers/application_mailer.rb, app/mailers/confirmation_mailer.rb, app/mailers/connection_request_mailer.rb, app/models/user.rb, app/views/confirmation_mailer/confirm.html.erb, app/views/confirmation_mailer/confirm.text.erb, app/views/confirmation_mailer/decline.html.erb, app/views/confirmation_mailer/decline.text.erb, app/views/connection_request_mailer/connect.html.erb, app/views/connection_request_mailer/connect.text.erb, config/routes.rb, db/migrate/20190213181758_create_messages.rb, db/schema.rb, spec/models/user_spec.rb, spec/requests/api/v1/login_request_spec.rb, spec/requests/api/v1/message_request_spec.rb
When user wants to connect with another user, a post /mailers endpoint is hit which creates an email with an embedded form.  Within the email, the user can either select a date/location and confirm the meeting or 'raincheck' the meeting.  When either button is clicked, another endpoint is hit at POST /api/v1/users/:id/messages which creates the message with the associated data.  This branch also tests these new endpoints.
closes #20 
closes #2
=> 20 email form spike

Gemfile, Gemfile.lock, README.md, app/controllers/api/v1/users_controller.rb, app/serializers/connection_serializer.rb, app/serializers/profile_serializer.rb, app/serializers/user_serializer.rb, app/services/github_service.rb, db/migrate/20190213181121_create_users.rb, db/schema.rb, db/seeds.rb, spec/requests/api/v1/user_update_spec.rb
User gets photos from github when they make a account
closes #69
=> 69 GitHub photos

.gitignore
create new elastic beanstalk environment from the CLI and this was added to the .gitignore file -
.elasticbeanstalk/*
!.elasticbeanstalk/*.cfg.yml
!.elasticbeanstalk/*.global.yml
closes #72
=> Add elastic beanstalk

app/models/user.rb
Adds photos to user methods in model
closes #75
=> Add photos in select for user methods
